package main

type AutoGenerated struct {
	Env []struct {
		Name      string `yaml:"name"`
		Value     string `yaml:"value,omitempty"`
		ValueFrom struct {
			FieldRef struct {
				FieldPath string `yaml:"fieldPath"`
			} `yaml:"fieldRef"`
		} `yaml:"valueFrom,omitempty"`
	} `yaml:"env"`
}